# wrangler.toml
name = "sprite-sheet-1"
main = "index.js"
compatibility_date = "2025-09-24"

# NUEVA SECCIÓN
[build]
command = "npm install"
watch_dir = "./" # Opcional: le dice a wrangler que observe cambios en todo el directorio

# Añade esta sección para vincular el secreto
[[vars]]
CLERK_SECRET_KEY = "CLERK_SECRET_KEY"
