# wrangler.toml
name = "sprite-sheet-1"
main = "index.js"
compatibility_date = "2025-09-24"

# NUEVA SECCIÓN
[build]
command = "npm install" # Primero instala las dependencias
entry = "index.js"      # Especifica el punto de entrada
upload.format = "modules" # Le dice a Wrangler que empaquete el código como un módulo ES

# Añade esta sección para vincular el secreto
[[vars]]
CLERK_SECRET_KEY = "CLERK_SECRET_KEY"
