# wrangler.toml
name = "sprite-sheet-1"
main = "index.js"
compatibility_date = "2025-09-24"

# Indica a Wrangler que el directorio actual contiene los archivos est치ticos
# que se subir치n a un bucket de KV para ser servidos.
[site]
bucket = "."

[build]
command = "npm install"

# A침ade esta secci칩n para vincular el secreto
[[vars]]
CLERK_SECRET_KEY = "CLERK_SECRET_KEY"
